title: Junchen Lv's Homepage
page-top-title: Junchen Lv
top-section-bg-text: Be what you wanna be
home-subtitle: Junchen Lv&ensp;|&ensp;吕俊辰
copyright-text: '&copy; Junchen Lv 2023-2025. All Rights Reserved.'
